stages:
  clean:
    cmd: python scripts/clean_data.py
    deps:
      - data/raw/insurance_data.csv
      - scripts/clean_data.py
    outs:
      - data/processed/insurance_data_cleaned.csv
  enhance:
    cmd: python scripts/create_second_version.py
    deps:
      - data/processed/insurance_data_cleaned.csv
      - scripts/create_second_version.py
    outs:
      - data/processed/insurance_data_enhanced.csv
